<a href="https://colab.research.google.com/github/torcodex/Python-Practices/blob/main/EDA_Case_Study2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv('/content/drive/MyDrive/commodity_prices.csv')
df

,Unnamed: 0,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world
0,1,1960-01-01,1.63,1.63,0.940900,0.696864,0.930301,1.121401,1.037400,0.122356,0.116845,0.066600
1,2,1960-02-01,1.63,1.63,0.946900,0.688707,0.930301,1.121401,1.037400,0.122356,0.119049,0.067900
2,3,1960-03-01,1.63,1.63,0.928100,0.688707,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300
3,4,1960-04-01,1.63,1.63,0.930300,0.684519,0.930301,1.121401,1.037400,0.122356,0.123459,0.068100
4,5,1960-05-01,1.63,1.63,0.920000,0.690692,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300
...,...,...,...,...,...,...,...,...,...,...,...,...
751,752,2022-08-01,98.60,97.75,5.917861,2.417366,4.210000,3.538154,2.360000,0.330773,0.782199,0.393525
752,753,2022-09-01,90.16,90.63,5.897138,2.455065,4.490000,3.153198,2.360000,0.323621,0.770956,0.390659
753,754,2022-10-01,93.13,90.59,5.292852,2.270979,4.135621,2.833112,2.457500,0.320943,0.762578,0.386911
754,755,2022-11-01,91.07,86.28,4.715462,2.041258,3.831528,2.849979,2.490000,0.332993,0.792340,0.407414
755,756,2022-12-01,80.90,76.78,4.629482,2.045446,3.994073,2.421516,2.386667,0.345729,0.805127,0.417335

In [9]:
df.drop(columns={'Unnamed: 0'}, inplace=True)
df.head(10)

,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world
0,1960-01-01,1.63,1.63,0.9409,0.696864,0.930301,1.121401,1.0374,0.122356,0.116845,0.0666
1,1960-02-01,1.63,1.63,0.9469,0.688707,0.930301,1.121401,1.0374,0.122356,0.119049,0.0679
2,1960-03-01,1.63,1.63,0.9281,0.688707,0.930301,1.121401,1.0374,0.122356,0.121254,0.0683
3,1960-04-01,1.63,1.63,0.9303,0.684519,0.930301,1.121401,1.0374,0.122356,0.123459,0.0681
4,1960-05-01,1.63,1.63,0.9200,0.690692,0.930301,1.121401,1.0374,0.122356,0.121254,0.0683
5,1960-06-01,1.63,1.63,0.9123,0.696864,0.930301,1.121401,1.0374,0.122356,0.125663,0.0666
6,1960-07-01,1.63,1.63,0.9160,0.690692,0.930301,1.121401,1.0374,0.122356,0.132277,0.0728
7,1960-08-01,1.63,1.63,0.9292,0.698848,0.930301,1.121401,1.0374,0.122356,0.127868,0.0741
8,1960-09-01,1.63,1.63,0.9226,0.702817,0.930301,1.121401,1.0374,0.122356,0.132277,0.0725
9,1960-10-01,1.63,1.63,0.9237,0.706785,0.930301,1.121401,1.0374,0.122356,0.130073,0.0538

In [11]:
df.isna().sum()

date               0
oil_brent          0
oil_dubai          0
coffee_arabica     0
coffee_robustas    0
tea_columbo        0
tea_kolkata        0
tea_mombasa        0
sugar_eu           0
sugar_us           0
sugar_world        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [35]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             756 non-null    datetime64[ns]
 1   oil_brent        756 non-null    float64
 2   oil_dubai        756 non-null    float64
 3   coffee_arabica   756 non-null    float64
 4   coffee_robustas  756 non-null    float64
 5   tea_columbo      756 non-null    float64
 6   tea_kolkata      756 non-null    float64
 7   tea_mombasa      756 non-null    float64
 8   sugar_eu         756 non-null    float64
 9   sugar_us         756 non-null    float64
 10  sugar_world      756 non-null    float64
dtypes: datetime64[ns](1), float64(10)
memory usage: 65.1 KB

In [37]:
df = df.sort_values(by='date')
df

,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world
0,1960-01-01,1.63,1.63,0.940900,0.696864,0.930301,1.121401,1.037400,0.122356,0.116845,0.066600
1,1960-02-01,1.63,1.63,0.946900,0.688707,0.930301,1.121401,1.037400,0.122356,0.119049,0.067900
2,1960-03-01,1.63,1.63,0.928100,0.688707,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300
3,1960-04-01,1.63,1.63,0.930300,0.684519,0.930301,1.121401,1.037400,0.122356,0.123459,0.068100
4,1960-05-01,1.63,1.63,0.920000,0.690692,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300
...,...,...,...,...,...,...,...,...,...,...,...
751,2022-08-01,98.60,97.75,5.917861,2.417366,4.210000,3.538154,2.360000,0.330773,0.782199,0.393525
752,2022-09-01,90.16,90.63,5.897138,2.455065,4.490000,3.153198,2.360000,0.323621,0.770956,0.390659
753,2022-10-01,93.13,90.59,5.292852,2.270979,4.135621,2.833112,2.457500,0.320943,0.762578,0.386911
754,2022-11-01,91.07,86.28,4.715462,2.041258,3.831528,2.849979,2.490000,0.332993,0.792340,0.407414
755,2022-12-01,80.90,76.78,4.629482,2.045446,3.994073,2.421516,2.386667,0.345729,0.805127,0.417335

In [39]:
print(df['date'].min())
print(df['date'].max())

1960-01-01 00:00:00
2022-12-01 00:00:00

In [42]:
oil_df = df[['date','oil_brent','oil_dubai']]
oil_df

          date  oil_brent  oil_dubai
0   1960-01-01       1.63       1.63
1   1960-02-01       1.63       1.63
2   1960-03-01       1.63       1.63
3   1960-04-01       1.63       1.63
4   1960-05-01       1.63       1.63
..         ...        ...        ...
751 2022-08-01      98.60      97.75
752 2022-09-01      90.16      90.63
753 2022-10-01      93.13      90.59
754 2022-11-01      91.07      86.28
755 2022-12-01      80.90      76.78

[756 rows x 3 columns]

In [45]:
coffee_df = df[['date','coffee_arabica','coffee_robustas']]
coffee_df

          date  coffee_arabica  coffee_robustas
0   1960-01-01        0.940900         0.696864
1   1960-02-01        0.946900         0.688707
2   1960-03-01        0.928100         0.688707
3   1960-04-01        0.930300         0.684519
4   1960-05-01        0.920000         0.690692
..         ...             ...              ...
751 2022-08-01        5.917861         2.417366
752 2022-09-01        5.897138         2.455065
753 2022-10-01        5.292852         2.270979
754 2022-11-01        4.715462         2.041258
755 2022-12-01        4.629482         2.045446

[756 rows x 3 columns]

In [46]:
df.columns

Index(['date', 'oil_brent', 'oil_dubai', 'coffee_arabica', 'coffee_robustas',
       'tea_columbo', 'tea_kolkata', 'tea_mombasa', 'sugar_eu', 'sugar_us',
       'sugar_world'],
      dtype='object')

In [48]:
tea_df = df[['date','tea_columbo','tea_kolkata','tea_mombasa']]
tea_df

          date  tea_columbo  tea_kolkata  tea_mombasa
0   1960-01-01     0.930301     1.121401     1.037400
1   1960-02-01     0.930301     1.121401     1.037400
2   1960-03-01     0.930301     1.121401     1.037400
3   1960-04-01     0.930301     1.121401     1.037400
4   1960-05-01     0.930301     1.121401     1.037400
..         ...          ...          ...          ...
751 2022-08-01     4.210000     3.538154     2.360000
752 2022-09-01     4.490000     3.153198     2.360000
753 2022-10-01     4.135621     2.833112     2.457500
754 2022-11-01     3.831528     2.849979     2.490000
755 2022-12-01     3.994073     2.421516     2.386667

[756 rows x 4 columns]

In [51]:
recent_df = df[df['date'].dt.year >= 2015]
recent_df

,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world
660,2015-01-01,48.07,45.98,4.188778,2.160748,3.240000,2.283636,2.320000,0.380312,0.556446,0.338189
661,2015-02-01,57.93,55.83,3.943845,2.168464,3.110000,1.835830,2.417500,0.370874,0.542777,0.321654
662,2015-03-01,55.79,54.91,3.543706,2.031778,3.080000,1.424050,2.724000,0.353795,0.530652,0.290128
663,2015-04-01,59.39,58.80,3.615577,2.029573,3.010000,2.126130,2.767500,0.352456,0.537707,0.288364
664,2015-05-01,64.56,63.69,3.493882,1.930365,2.970000,2.595660,3.092500,0.364604,0.542557,0.294096
...,...,...,...,...,...,...,...,...,...,...,...
751,2022-08-01,98.60,97.75,5.917861,2.417366,4.210000,3.538154,2.360000,0.330773,0.782199,0.393525
752,2022-09-01,90.16,90.63,5.897138,2.455065,4.490000,3.153198,2.360000,0.323621,0.770956,0.390659
753,2022-10-01,93.13,90.59,5.292852,2.270979,4.135621,2.833112,2.457500,0.320943,0.762578,0.386911
754,2022-11-01,91.07,86.28,4.715462,2.041258,3.831528,2.849979,2.490000,0.332993,0.792340,0.407414
755,2022-12-01,80.90,76.78,4.629482,2.045446,3.994073,2.421516,2.386667,0.345729,0.805127,0.417335

In [52]:
period_df = df[(df['date'].dt.year >= 2000)&(df['date'].dt.year<=2010)]
period_df

,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world
480,2000-01-01,25.380000,23.280000,2.449600,1.172400,1.827300,1.861200,1.876000,0.600100,0.390000,0.124100
481,2000-02-01,27.704800,24.677100,2.280500,1.077200,1.808000,1.523600,2.105000,0.585100,0.376500,0.117300
482,2000-03-01,27.470000,25.080000,2.220700,1.019600,1.824500,1.367100,2.062500,0.577800,0.405400,0.112700
483,2000-04-01,22.540000,22.030000,2.085800,0.980000,1.811100,1.525400,2.030000,0.579400,0.427900,0.132500
484,2000-05-01,27.340000,25.390000,2.075600,0.977100,1.710200,2.200300,2.010000,0.554700,0.421500,0.152600
...,...,...,...,...,...,...,...,...,...,...,...
607,2010-08-01,76.693182,74.183810,4.664755,1.822780,3.269552,3.202597,2.508000,0.432058,0.771727,0.408075
608,2010-09-01,77.786818,75.270476,4.909909,1.791915,3.348809,3.181770,2.457500,0.439011,0.841503,0.496260
609,2010-10-01,82.918095,80.340476,4.798135,1.879879,3.372414,3.246775,2.485000,0.454100,0.842879,0.542557
610,2010-11-01,85.670000,83.696000,5.147347,2.029132,3.397942,3.165752,2.517500,0.445476,0.856211,0.580917
611,2010-12-01,91.796522,89.074545,5.471205,2.074327,3.502763,2.937479,2.686667,0.431944,0.846855,0.616873

In [55]:
df['month'] = df['date'].dt.month_name()
df

,date,oil_brent,oil_dubai,coffee_arabica,coffee_robustas,tea_columbo,tea_kolkata,tea_mombasa,sugar_eu,sugar_us,sugar_world,month
0,1960-01-01,1.63,1.63,0.940900,0.696864,0.930301,1.121401,1.037400,0.122356,0.116845,0.066600,January
1,1960-02-01,1.63,1.63,0.946900,0.688707,0.930301,1.121401,1.037400,0.122356,0.119049,0.067900,February
2,1960-03-01,1.63,1.63,0.928100,0.688707,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300,March
3,1960-04-01,1.63,1.63,0.930300,0.684519,0.930301,1.121401,1.037400,0.122356,0.123459,0.068100,April
4,1960-05-01,1.63,1.63,0.920000,0.690692,0.930301,1.121401,1.037400,0.122356,0.121254,0.068300,May
...,...,...,...,...,...,...,...,...,...,...,...,...
751,2022-08-01,98.60,97.75,5.917861,2.417366,4.210000,3.538154,2.360000,0.330773,0.782199,0.393525,August
752,2022-09-01,90.16,90.63,5.897138,2.455065,4.490000,3.153198,2.360000,0.323621,0.770956,0.390659,September
753,2022-10-01,93.13,90.59,5.292852,2.270979,4.135621,2.833112,2.457500,0.320943,0.762578,0.386911,October
754,2022-11-01,91.07,86.28,4.715462,2.041258,3.831528,2.849979,2.490000,0.332993,0.792340,0.407414,November
755,2022-12-01,80.90,76.78,4.629482,2.045446,3.994073,2.421516,2.386667,0.345729,0.805127,0.417335,December

In [62]:
monthly_oil_brent = df.groupby('month')['oil_brent'].max().sort_values(ascending=False).round(1)
monthly_oil_brent.head(10)

month
July         133.9
June         133.0
March        124.9
May          123.9
April        123.1
February     119.7
August       113.8
September    113.4
January      113.0
October      112.0
Name: oil_brent, dtype: float64

In [63]:
df.nlargest(10,'oil_brent')[['date','oil_brent']]

          date   oil_brent
582 2008-07-01  133.873043
581 2008-06-01  133.048571
626 2012-03-01  124.928636
580 2008-05-01  123.936190
615 2011-04-01  123.070000
627 2012-04-01  120.463500
749 2022-06-01  120.080000
625 2012-02-01  119.702381
637 2013-02-01  116.519500
618 2011-07-01  116.460000

In [64]:
df.nsmallest(10,'sugar_world')[['date','sugar_world']]

          date  sugar_world
84  1967-01-01       0.0287
83  1966-12-01       0.0298
104 1968-09-01       0.0304
82  1966-11-01       0.0311
80  1966-09-01       0.0329
81  1966-10-01       0.0337
103 1968-08-01       0.0337
86  1967-03-01       0.0346
79  1966-08-01       0.0359
102 1968-07-01       0.0359

In [66]:
oil_price_gap = df['oil_brent']-df['oil_dubai']
oil_price_gap

0      0.00
1      0.00
2      0.00
3      0.00
4      0.00
       ...
751    0.85
752   -0.47
753    2.54
754    4.79
755    4.12
Length: 756, dtype: float64

In [69]:
coffee_price_gap = df['coffee_arabica'] - df['coffee_robustas']
coffee_price_gap

0      0.244036
1      0.258193
2      0.239393
3      0.245781
4      0.229309
         ...
751    3.500496
752    3.442073
753    3.021873
754    2.674204
755    2.584035
Length: 756, dtype: float64

In [73]:
sugar_avg_df = df.groupby('month').agg(
    avg_sugar = ('sugar_world','mean'),
    avg_eu_sugar = ('sugar_eu','mean'),
    avg_us_sugar = ('sugar_us','mean')
)
sugar_avg_df

           avg_sugar  avg_eu_sugar  avg_us_sugar
month
April       0.232953      0.404623      0.425992
August      0.237115      0.405719      0.434951
December    0.246300      0.405975      0.436708
February    0.247193      0.402805      0.431422
January     0.245496      0.409266      0.429066
July        0.238054      0.407148      0.432158
June        0.232175      0.402070      0.428346
March       0.239048      0.402715      0.427164
May         0.233348      0.403765      0.426936
November    0.251288      0.404480      0.443144
October     0.244883      0.406377      0.439191
September   0.235309      0.406951      0.434469

In [74]:
df.columns

Index(['date', 'oil_brent', 'oil_dubai', 'coffee_arabica', 'coffee_robustas',
       'tea_columbo', 'tea_kolkata', 'tea_mombasa', 'sugar_eu', 'sugar_us',
       'sugar_world', 'month'],
      dtype='object')

In [78]:
df[['oil_brent','oil_dubai','coffee_arabica','coffee_robustas','sugar_world']].describe().T['mean']

oil_brent          32.724944
oil_dubai          31.238130
coffee_arabica      2.576555
coffee_robustas     1.727478
sugar_world         0.240263
Name: mean, dtype: float64