<a href="https://colab.research.google.com/github/torcodex/Python-Practices/blob/main/EDA_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/purchase_case_study_inferential_statistics.csv')
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263010,1004473,P00041942,M,36-45,1.0,B,3,0.0,5.0,18.0,NaN,3722.0
263011,1004473,P00115142,M,36-45,1.0,B,3,0.0,1.0,8.0,17.0,19253.0
263012,1004473,P00188442,M,36-45,1.0,B,3,0.0,5.0,7.0,NaN,3608.0
263013,1004473,P00119442,M,36-45,1.0,B,3,0.0,5.0,NaN,NaN,3604.0
263014,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263015 entries, 0 to 263014
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     263015 non-null  int64
 1   Product_ID                  263014 non-null  object
 2   Gender                      263014 non-null  object
 3   Age                         263014 non-null  object
 4   Occupation                  263014 non-null  float64
 5   City_Category               263014 non-null  object
 6   Stay_In_Current_City_Years  263014 non-null  object
 7   Marital_Status              263014 non-null  float64
 8   Product_Category_1          263014 non-null  float64
 9   Product_Category_2          181501 non-null  float64
 10  Product_Category_3          80582 non-null   float64
 11  Purchase                    263014 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 24.1+ MB

In [ ]:
df.isna().sum()

User_ID                            0
Product_ID                         1
Gender                             1
Age                                1
Occupation                         1
City_Category                      1
Stay_In_Current_City_Years         1
Marital_Status                     1
Product_Category_1                 1
Product_Category_2             81514
Product_Category_3            182433
Purchase                           1
dtype: int64

In [ ]:
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                    float64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                float64
Product_Category_1            float64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
dtype: object

In [ ]:
df['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0', nan], dtype=object)

In [ ]:
df['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].replace('4+', '4')

In [ ]:
df[df['Product_ID'].isna()].index

Index([263014], dtype='int64')

In [ ]:
df = df.drop(263014)
df.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             81513
Product_Category_3            182432
Purchase                           0
dtype: int64

In [ ]:
df[df['Product_Category_3'].notnull()]

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
6,1000004,P00184942,M,46-50,7.0,B,2,1.0,1.0,8.0,17.0,19215.0
13,1000005,P00145042,M,26-35,20.0,A,1,1.0,1.0,2.0,5.0,15665.0
14,1000006,P00231342,F,51-55,9.0,A,1,0.0,5.0,8.0,14.0,5378.0
16,1000006,P0096642,F,51-55,9.0,A,1,0.0,2.0,3.0,4.0,13055.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262997,1004472,P00262242,F,46-50,16.0,B,0,1.0,1.0,11.0,16.0,15175.0
263001,1004472,P00209742,F,46-50,16.0,B,0,1.0,1.0,11.0,15.0,15430.0
263003,1004472,P00345742,F,46-50,16.0,B,0,1.0,1.0,2.0,15.0,15387.0
263006,1004472,P00034142,F,46-50,16.0,B,0,1.0,8.0,13.0,16.0,5861.0
263011,1004473,P00115142,M,36-45,1.0,B,3,0.0,1.0,8.0,17.0,19253.0

In [ ]:
next = df.groupby('Occupation')[['Product_Category_3']].mean().round(1)
next

            Product_Category_3
Occupation
0.0                       12.6
1.0                       12.7
2.0                       12.6
3.0                       12.6
4.0                       12.5
5.0                       12.5
6.0                       12.7
7.0                       12.8
8.0                       12.2
9.0                       12.4
10.0                      11.9
11.0                      12.8
12.0                      12.8
13.0                      13.2
14.0                      12.7
15.0                      12.9
16.0                      12.9
17.0                      12.8
18.0                      12.7
19.0                      12.5
20.0                      12.6