<a href="https://colab.research.google.com/github/torcodex/Python-Practices/blob/main/PandasHandson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Order_ID': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
                 1011,1012,1013,1014,1015,1015],

    'Customer': ['Rahul','Priya','Amit','Sneha','Arjun','Neha','Rohan',
                 'Anjali','Vikas','Pooja','Karan','Meera',None,'Simran',
                 'Nikhil','Nikhil'],

    'City': ['Bangalore','Mumbai','Delhi','Bangalore','Mumbai','Delhi',
             'Pune','Pune','Bangalore','Mumbai','Delhi',None,'Chennai',
             'Mumbai','Bangalore','Bangalore'],

    'Product': ['Laptop','Mobile','Headphones','Laptop','Tablet','Mobile',
                'Laptop','Headphones','Mobile','Tablet','Laptop','Mobile',
                'Headphones','Laptop',None,'Laptop'],

    'Quantity': [1,2,3,1,2,1,1,4,2,3,1,2,3,1,None,1],

    'Price': [60000,25000,2000,58000,30000,24000,62000,1800,26000,
              28000,61000,23000,2200,59000,29000,59000],

    'Discount': [5,10,0,8,5,None,10,0,5,10,12,5,0,7,10,7],

    'Payment_Mode': ['UPI','Card','UPI','Card','Cash','UPI','Card',
                     'UPI','card','Cash','UPI','Card','UPI','CARD',
                     'UPI','CARD']
}

df = pd.DataFrame(data)

In [ ]:
df.shape

(16, 8)

In [ ]:
df.dtypes

Order_ID          int64
Customer         object
City             object
Product          object
Quantity        float64
Price             int64
Discount        float64
Payment_Mode     object
dtype: object

In [ ]:
df.isna().sum()

Order_ID        0
Customer        0
City            0
Product         0
Quantity        0
Price           0
Discount        0
Payment_Mode    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates("Order_ID", keep='last', inplace = True)

In [ ]:
df['Discount'] = df['Discount'].fillna(df.groupby('Product')['Discount'].transform('median'))
df['Customer'] = df['Customer'].fillna('Unknown')
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [ ]:
df['Payment_Mode'] = df['Payment_Mode'].str.upper()

In [ ]:
df

,Order_ID,Customer,City,Product,Quantity,Price,Discount,Payment_Mode,Gross_Amount,Discount_Amount,Final_Amount
0,1001,Rahul,Bangalore,Laptop,1.0,60000,5.0,UPI,60000.0,3000.0,57000.0
1,1002,Priya,Mumbai,Mobile,2.0,25000,10.0,CARD,50000.0,5000.0,45000.0
2,1003,Amit,Delhi,Headphones,3.0,2000,0.0,UPI,6000.0,0.0,6000.0
3,1004,Sneha,Bangalore,Laptop,1.0,58000,8.0,CARD,58000.0,4640.0,53360.0
4,1005,Arjun,Mumbai,Tablet,2.0,30000,5.0,CASH,60000.0,3000.0,57000.0
5,1006,Neha,Delhi,Mobile,1.0,24000,5.0,UPI,24000.0,1200.0,22800.0
6,1007,Rohan,Pune,Laptop,1.0,62000,10.0,CARD,62000.0,6200.0,55800.0
7,1008,Anjali,Pune,Headphones,4.0,1800,0.0,UPI,7200.0,0.0,7200.0
8,1009,Vikas,Bangalore,Mobile,2.0,26000,5.0,CARD,52000.0,2600.0,49400.0
9,1010,Pooja,Mumbai,Tablet,3.0,28000,10.0,CASH,84000.0,8400.0,75600.0
10,1011,Karan,Delhi,Laptop,1.0,61000,12.0,UPI,61000.0,7320.0,53680.0
11,1012,Meera,Bangalore,Mobile,2.0,23000,5.0,CARD,46000.0,2300.0,43700.0
12,1013,Unknown,Chennai,Headphones,3.0,2200,0.0,UPI,6600.0,0.0,6600.0
13,1014,Simran,Mumbai,Laptop,1.0,59000,7.0,CARD,59000.0,4130.0,54870.0
15,1015,Nikhil,Bangalore,Laptop,1.0,59000,7.0,CARD,59000.0,4130.0,54870.0

In [ ]:
df['Gross_Amount'] = df['Quantity'] * df['Price']
df['Discount_Amount'] = df['Gross_Amount'] * (df['Discount'] / 100)
df['Final_Amount'] = df['Gross_Amount'] - df['Discount_Amount']

In [ ]:
df['Order_ID'].count()

np.int64(15)

In [ ]:
df['Quantity'].sum()

np.float64(28.0)

In [ ]:
df['Final_Amount'].sum()

np.float64(642880.0)

In [ ]:
df['Price'].mean()

np.float64(34733.333333333336)

In [ ]:
product_revenue = df.groupby('Product')['Final_Amount'].sum()

product_revenue.sort_values(ascending=False)

Product
Laptop        329580.0
Mobile        160900.0
Tablet        132600.0
Headphones     19800.0
Name: Final_Amount, dtype: float64

In [ ]:
df.groupby('City')['Order_ID'].count()

City
Bangalore    5
Chennai      1
Delhi        3
Mumbai       4
Pune         2
Name: Order_ID, dtype: int64

In [ ]:
df.groupby('City')['Final_Amount'].sum()

City
Bangalore    258330.0
Chennai        6600.0
Delhi         82480.0
Mumbai       232470.0
Pune          63000.0
Name: Final_Amount, dtype: float64

In [ ]:
df.groupby('City')['Price'].mean()

City
Bangalore    45200.0
Chennai       2200.0
Delhi        29000.0
Mumbai       35500.0
Pune         31900.0
Name: Price, dtype: float64

In [ ]:
df.groupby('Payment_Mode')['Order_ID'].count()

Payment_Mode
CARD    7
CASH    2
UPI     6
Name: Order_ID, dtype: int64

In [ ]:
df.groupby('Payment_Mode')['Final_Amount'].sum()

Payment_Mode
CARD    357000.0
CASH    132600.0
UPI     153280.0
Name: Final_Amount, dtype: float64

In [ ]:
df.groupby('Payment_Mode')['Payment_Mode'].count().head(1)

Payment_Mode
CARD    7
Name: Payment_Mode, dtype: int64

In [ ]:
product_revenue.sort_values(ascending=False).head(1)

Product
Laptop    329580.0
Name: Final_Amount, dtype: float64

In [ ]:
df.groupby('Product')['Quantity'].sum().head(1)

Product
Headphones    10.0
Name: Quantity, dtype: float64

In [ ]:
df.groupby('City')['Final_Amount'].sum().head(1)

City
Bangalore    258330.0
Name: Final_Amount, dtype: float64

In [ ]:
df.sort_values(by='Price',ascending=False).head(1)['Customer']

6    Rohan
Name: Customer, dtype: object

In [ ]:
df.groupby('Payment_Mode')['Payment_Mode'].count().head(1)

Payment_Mode
CARD    7
Name: Payment_Mode, dtype: int64

In [ ]:
product_revenue = df.groupby('Product')['Final_Amount'].sum()
amt=product_revenue.max()
total = df['Final_Amount'].sum()
percent = (amt/total)*100
print(percent)

51.266177202588345

329580.0